# Generated by Django 2.1.7 on 2019-04-01 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probecard_id', models.CharField(max_length=30)),
                ('device_num', models.CharField(max_length=30)),
                ('device_name', models.CharField(help_text='Enter device group name (e.g. Merle)', max_length=10)),
                ('aus_serial_num', models.CharField(help_text='Enter probecard serial number', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProbeCardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probehead_rebuild_num', models.IntegerField(default=0)),
                ('probehead_num', models.CharField(help_text='Probehead serial number', max_length=20)),
                ('date_measured', models.DateField(blank=True, null=True)),
                ('tip_length', models.DecimalField(blank=True, decimal_places=1, help_text='Enter tip lenght in 1 dec place', max_digits=4, null=True)),
                ('crown_height', models.DecimalField(blank=True, decimal_places=1, help_text='Enter crown height in 1 dec place', max_digits=4, null=True)),
                ('probehead_touchdown', models.IntegerField(blank=True, null=True)),
                ('pcb_touchdown', models.IntegerField(blank=True, null=True)),
                ('iqa_date', models.DateField(blank=True, null=True)),
                ('iqa_tip_length', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('crown_iqa_height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateField(default=datetime.date(2019, 4, 2))),
                ('status_log', models.CharField(blank=True, choices=[('r', 'Rebuilt'), ('a', 'Active'), ('o', 'Obsolete'), ('b', 'Shipped Back'), ('s', 'Swap PH'), ('d', 'Damaged')], default='', help_text='Status base on Remarks', max_length=1)),
                ('status_pc', models.CharField(blank=True, choices=[('g', 'Good'), ('b', 'Bad')], default='', help_text='ProbeCard Status', max_length=1)),
                ('status_prod', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='', help_text='In Production?', max_length=1)),
                ('probecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockcontrol.ProbeCard')),
            ],
            options={
                'ordering': ['probecard', 'probehead_num'],
            },
        ),
    ]
