# Generated by Django 2.1.7 on 2019-04-28 14:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probecardreport',
            options={'ordering': ['probecard', 'probehead_rebuild_num'], 'permissions': (('can_edit_status', 'Edit ProbeCard status'),)},
        ),
        migrations.AddField(
            model_name='probecardreport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='probecard',
            name='device_name',
            field=models.CharField(help_text='Enter device group name (e.g. Merle)', max_length=20),
        ),
        migrations.AlterField(
            model_name='probecardreport',
            name='date_added',
            field=models.DateField(default=datetime.date(2019, 4, 28)),
        ),
        migrations.AlterField(
            model_name='probecardreport',
            name='date_measured',
            field=models.DateField(blank=True, help_text='Enter date in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='probecardreport',
            name='iqa_date',
            field=models.DateField(blank=True, help_text='Enter date in YYYY-MM-DD format', null=True),
        ),
    ]
